site_name: Learn Appleseed 
site_url: http://appleseedapp.net/
site_description: Open Source .NET Enterprise Software.
site_author: Team @ Anant Corporation (www.anant.us)
repo_url: https://github.com/Appleseed/learn
theme: readthedocs
pages:
# Introduction: 
- ['index.md', 'About', 'Appleseed Framework']
- ['portal/index.md','About','Appleseed Portal']
- ['portal/release-notes.md','About','Appleseed Portal Release Notes']
- ['portal/intro/understanding-appleseed.md','About','Understanding Appleseed Portal ']
# Installation:
- ['portal/install/index.md', 'Installation','Overview']
- ['portal/install/windows.md', 'Installation','Windows']
- ['portal/install/amazon.md', 'Installation','Amazon']
- ['portal/install/azure.md', 'Installation','Azure']
# User:
- ['portal/user/index.md', 'User Guide','Overview']
- ['portal/user/getting-started.md', 'User Guide', 'Getting Started']
# Builder:
- ['portal/builder/index.md', 'Builder Guide']
- ['portal/user/getting-started.md', 'Builder Guide', 'Getting Started']
# Administrator:
- ['portal/admin/index.md', 'Administrator Guide']
- ['portal/user/getting-started.md', 'Administrator Guide', 'Getting Started']
# Designer:
- ['portal/designer/index.md', 'Designer Guide']
- ['user/getting-started.md', 'Designer Guide', 'Getting Started']
# Developer:
- ['portal/developer/index.md', 'Developer Guide']
- ['portal/user/getting-started.md', 'Developer Guide', 'Getting Started']


copyright: Copyright &copy; 2015, <a href="http://www.anant.us">Anant Corporation</a>.
